### PR TITLE
Adding embrace-ruby-mode-hook function.

### PR DESCRIPTION
**Pull request by dcluna**
This function introduces a few useful embraces for Ruby: do/end blocks
and string interpolation.

### CODE REVIEW

**Comment by cute-jumper** [comment]
Thanks. A little problem here:

```
'((?# "#{" "}")
  (?d "do" "end"))
```

should be

```
'((?# "#{" . "}")
  (?d "do" . "end"))
```

Or you have to use `caddr` or `(nth 2 lst)` for the third element.

Could you update the PR? :-)

I'm planning to add some new API to make switching between `do/end` block and `{}` block more intelligently. Do you have any suggestions?

**Comment by dcluna** [comment]
Thanks for your review. This commit was also missing the closing parens on the `defun`. (Sorry for being a little haphazard, but I was more concerned w/ getting this out and discussing). There was also a [typo](https://github.com/cute-jumper/embrace.el/blob/master/embrace.el#L856) that I tried to fix, with no luck (Github reported a merge conflict, so I decided to back off).

Wrt/ the new API, what do you feel could be done more intelligently? I'm actually an `evil-embrace` user, and I think it works very fine for this purpose. If I could improve on something, it would be being able to choose between inner and outer blocks, as in the following code:

``` ruby
an_object.each do |a|
    a.inner_block_method do |b|
      b.method_call |
    end
end
```

With point in the `|` character, AFAIK I can only change the inner `do/end` block. I'd probably start with making [embrace--expand-region-research](https://github.com/cute-jumper/embrace.el/blob/master/embrace.el#L703) work with an optional N parameter. Being able to do something like `2csd` to solve this problem with `evil-embrace` in Ruby would be a killer feature IMHO.

**Comment by cute-jumper** [comment]
That would be nice, and it can also help `evil-surround` too. I would probably look into it if I have time.

Forgot to mention, but could you also update the README.org file accordingly too? Sorry about that.

**Comment by dcluna** [comment]
Done. I just didn't update a screencast, but I think the updated README should be enough.

**Comment by cute-jumper** [comment]
Awesome! Thanks.

**Pull request merged**
